### ISSUE TITLE
Reduce white border around "sure" rainbow partial hint

### ISSUE THREAD

**Issue by bstnfrmry** [bstnfrmry/hanabi#141]
![image](https://user-images.githubusercontent.com/1478542/81213326-7cee8080-8fd6-11ea-855e-5dc082ac9c2d.png)

The current white border makes you believe it could be white.

**Comment by spkuehl** [comment]
Would it be good to have an unused color (like gold?) for "sure" hints, for all colors?

**Comment by bstnfrmry** [comment]
Hey! I guess no border on rainbow cards would be the clearest.

**Comment by spkuehl** [comment]
How would you know between partial and sure hints?

**Comment by bstnfrmry** [comment]
Closing this in favor of #171 which is more elaborated.
