### ISSUE TITLE
Menu on mobile is too wide

### ISSUE THREAD

**Issue by sgiebels** [bstnfrmry/hanabi#172]
I've noticed that on mobile, the menu buttons are next to eachother, but too wide for the screen:
![Screenshot_20200605-142903](https://user-images.githubusercontent.com/11091585/83946406-e7caeb80-a810-11ea-9efd-2ef1b502a8c9.png)

**Comment by bstnfrmry** [comment]
Indeed thanks! I'd like to make it full screen and vertical at some point so we can add more stuff.
