### ISSUE TITLE
No software license specified for this project yet

### ISSUE THREAD

**Issue by sgiebels** [bstnfrmry/hanabi#173]
I did not find any mention of a license (GPL etc) on your Github project page for Hanabi. 

Could you (as a team) perhaps have a look at:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
and choose one that matches your preference for use with your code?

**Comment by bstnfrmry** [comment]
@sgiebels I added the MIT licence, thanks!
