### ISSUE TITLE
End of game "Reveal" button doesn't work anymore

### ISSUE THREAD

**Issue by rcfox** [bstnfrmry/hanabi#204]
For the past week or so, the button to reveal your own cards at the end of the game has stopped working. 

I think earlier, this also extended to the rewind feature: you wouldn't be able to see your cards during the end of game rewind. Trying it now though, hitting "reveal" and then "rewind" does show your cards. The change only takes place when switching in and our of rewind mode.

**Comment by sarahmamy** [comment]
Thanks @rcfox, I will investigate

**Comment by sarahmamy** [comment]
Hey, my PR is in review, it should be fixed soon if it passes the review

**Comment by sarahmamy** [comment]
Hey @rcfox it is fixed, thanks for spotting it! You can now also reveal your cards when replaying at the end of the game and use keyboard arrows to navigate in replay
