### ISSUE TITLE
Hint button is not clickable

### ISSUE THREAD

**Issue by PatrickJosh** [bstnfrmry/hanabi#210]
Currently, in every game I start, the "Hint" button is unclickable. That makes the game unplayable. This is the case for all of my friends as well, we have tested it with Chromium and Firefox and used different settings for our games. It way always the case.

**Comment by bstnfrmry** [comment]
Hey @PatrickJosh. Thanks for reporting the bug. It's fixed now 😉

**Comment by PatrickJosh** [comment]
Thank you! :smile:
