### ISSUE TITLE
in Rainbow, AI hints about the rainbow color

### ISSUE THREAD

**Issue by benjamintd** [bstnfrmry/hanabi#211]
Which is a bit cheating :)

**Comment by benjamintd** [comment]
bonus, this 4 is not of any color ? 
![image](https://user-images.githubusercontent.com/11202803/101750904-ed5f0200-3acf-11eb-94c1-01cc1cbe7520.png)

**Comment by bstnfrmry** [comment]
https://github.com/bstnfrmry/hanabi/issues/107 😉
