### ISSUE TITLE
"New Game" button puts all players in different rooms

### ISSUE THREAD

**Issue by not-an-aardvark** [bstnfrmry/hanabi#239]
Thanks for making this project!

Occasionally, after playing a game with multiple people, we want to play again. Everyone clicks the "New Game" button, and ends up in a newly-created game that appears to have the same participants. Then we end up in a very confusing state where nobody can see each others' moves.

This happens because when two players click the "New Game" button, they will actually create completely separate games. Confusingly, each new game makes it look like the other players are already present, but the other players typically will not end up in the same room without manual link-sharing.

To me, it seems like it would make more sense for the "New Game" button to send everyone in a particular game to the same new room. Maybe one way to do this would be to make the new game ID deterministic based on the previous game ID. 

Possibly in combination with the above: after one player creates a new game, the "New Game" button for the other players could get replaced with a "Join Next Game" button which is just a direct link to the new room..

**Comment by tarwebrood** [comment]
Can confirm that this issue is still present. Was playing a 3 player game today, finished, then everyone clicked 'New game'.
2 players were in room 'DifficultBasiliskAmaranth', and one of the players ended up in a different room.
It took a few minutes to figure out why the other player wasn't making a move. In his game, he was waiting on us..

**Comment by dcorbin** [comment]
I suspect this will not be addressed anytime soon.  If one player clicks "New Game", other players will be updated and "New Game" will become "Next Game", which they can then click on without problem.

**Comment by dcorbin** [comment]
This should no longer occur.  

Changed what makes a "Game ID" to be deterministic when create a new game after completing one.
