### ISSUE TITLE
Keep the language kid-friendly please

### ISSUE THREAD

**Issue by nburleigh6** [bstnfrmry/hanabi#248]
I played with "Prevent loss" enabled and when I made a mistake this popped up: "You fucked up. Keep going?"

I suggest keeping the language PG so that parents can feel comfortable playing with their young kids.

It's line 29 (preventLossContent) in \src\locales\en.ts

Thanks.

**Comment by benjamintd** [comment]
Thanks for the suggestion, that's fixed!

**Comment by nburleigh6** [comment]
Thanks for the quick fix!
