### ISSUE TITLE
At the end of the game, I can choose "Bouquet Final" variant

### ISSUE THREAD

**Issue by sarahmamy** [bstnfrmry/hanabi#74]
Game normal rules are "When the last card is drawn, each player has one more turn". But the rules provide another alternative ending versions

* Variante Bouquet Final "You can play until game ends"

**Comment by mikecmeli** [comment]
Is this the same as Royal Favor mentioned [here](https://en.wikipedia.org/wiki/Hanabi_(card_game))?

I would be happy contribute.

**Comment by bstnfrmry** [comment]
Hey @mikecmeli. Sorry about the delay, didn't see you message.

I implemented a basic version of this simply allowing players to keep playing when the game is over. (See https://github.com/bstnfrmry/hanabi/pull/119)

Did you have something specific in mind ?

**Comment by mikecmeli** [comment]
This looks like it covers my use case. Thanks!
