### ISSUE TITLE
Show what teammates know about their cards without having to select their game

### ISSUE THREAD

**Issue by bstnfrmry** [bstnfrmry/hanabi#83]

**Comment by sarahmamy** [comment]
maybe sthg like this @bstnfrmry  ? 

![image](https://user-images.githubusercontent.com/16375291/77853473-9127ac80-71e4-11ea-9cd8-a665bf5ceaf2.png)

**Comment by bstnfrmry** [comment]
Maybe another color or something if they know the card for sure?
