### ISSUE TITLE
Fireworks at win

### ISSUE THREAD

**Issue by brambex** [bstnfrmry/hanabi#93]
This game lends itself well to visual effects and would make the game more attractive to players. Why no on screen fireworks at win?
E.g. on win
![image](https://user-images.githubusercontent.com/62907760/77959403-d1ffee00-72d6-11ea-8f7a-b8e41e6fc55e.png)
show the page like:
![animation](https://user-images.githubusercontent.com/62907760/77959822-8c8ff080-72d7-11ea-8edd-5d18c44e715a.gif)

I've fast-coded it. If you wan't me to, I can create a branch and clean up the code.

**Comment by benjamintd** [comment]
This would be amazing ! Thanks for looking into it.
If you don't mind putting up a PR, we'd be glad to have you contribute to the project.

**Comment by brambex** [comment]
Ok, I'm not able to create a new branch though. Can you give me the right permissions?

**Comment by benjamintd** [comment]
The typical flow in this situation is to create a fork, create a branch there, then open a PR in this repo using your fork's branch. Would this work for you?

**Comment by sarahmamy** [comment]
Hey @brambex, do you need any help to fork the project? I'd be happy to help you. We really like your idea! Can't wait to test it!

**Comment by brambex** [comment]
Hey @sarahmamy, I've been quite busy lately but I've pushed changes today. I'll still need some help with ZEIT build though...
https://github.com/bstnfrmry/hanabi/pull/102

Please have a look at the code. Currently there will always be fireworks at the end of a game but the time span depends on the players score:
`timeout = game.playedCards.length * 200`  so in theory ranging from 0 to 5 seconds
